# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    http_client:
        scoped_clients:
            dsa.http_client:
                base_uri: 'https://dsa.fan'
