club:
    path: '/guilds/{id}'

player:
    path: '/players/{id}'

toon:
    path: '/characters/{id}'

toon_list:
    path: '/characters'

toon_progress:
  path: '/players/{playerId}/characters/{id}'
